version: '3'
services:
  database:
    image: mariadb:10
    environment:
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=njhfnjh1
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - /home/database:/var/lib/mysql
    restart: always
  app:
    image: devvetton/hedgedoc:master
    environment:
      - CMD_DB_URL=mysql://hedgedoc:njhfnjh1@database:3306/hedgedoc
      - CMD_DOMAIN=192.168.97.200
      - CMD_URL_ADDPORT=true
    volumes:
      - /home/uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database